before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
      - mips64
      - mips64le
      - mips
      - mipsle
    goarm:
      - 5
      - 6
      - 7
    binary: '{{ .ProjectName }}'
    main: main.go
archives:
  - format: zip
checksum:
  algorithm: sha256
